export default {
"login": "smajda",
"id": 68415,
"node_id": "MDQ6VXNlcjY4NDE1",
"avatar_url": "https://avatars.githubusercontent.com/u/68415?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/smajda",
"html_url": "https://github.com/smajda",
"followers_url": "https://api.github.com/users/smajda/followers",
"following_url": "https://api.github.com/users/smajda/following{/other_user}",
"gists_url": "https://api.github.com/users/smajda/gists{/gist_id}",
"starred_url": "https://api.github.com/users/smajda/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/smajda/subscriptions",
"organizations_url": "https://api.github.com/users/smajda/orgs",
"repos_url": "https://api.github.com/users/smajda/repos",
"events_url": "https://api.github.com/users/smajda/events{/privacy}",
"received_events_url": "https://api.github.com/users/smajda/received_events",
"type": "User",
"site_admin": false,
"name": "Jon Smajda",
"company": null,
"blog": "http://jon.smajda.com",
"location": "Kansas City",
"email": null,
"hireable": null,
"bio": null,
"twitter_username": null,
"public_repos": 33,
"public_gists": 18,
"followers": 26,
"following": 3,
"created_at": "2009-03-29T19:24:17Z",
"updated_at": "2021-05-05T21:18:28Z"
}